### ISSUE TITLE
diff_mean_test on batch-corrected Seurat object

### ISSUE THREAD

**Issue by peterras1985** [ChristophH/sctransform#102]
Hej Christoph,
I am following your vignette for the conserved marker finding in Seurat object after integration. My samples are quite different in nCount_RNA because the cell quantification was off ~5-fold and sequencing was done in equimolar pool. I am working with Seurat objects and integration workflow. In your vignette, you are saying that "_When working with data where there is a stark discrepancy between sequencing depth, one should make sure that the corrected counts used for differential expression testing were generated using the same ‘target’ depth. Since this is not supported by Seurat::SCTransform it requires running sctransform::correct() with identical cell meta data for all samples and setting the as_is parameter to TRUE._". 
Maybe I misunderstood SCTransform in Seurat, but is the result not the same (corrected UMI counts in "counts") if I run Seurat::SCTransform after integration on the full count matrix in the RNA assay?
e.g. SCTransform -> FindIntegrationAnchors -> IntegrateData -> SCTransform(assay = "RNA")
Thank you!

**Comment by ChristophH** [comment]
Hello,

Now that I re-read that paragraph in the vignette, I realize that the statement is an error. The point I was trying to make is that the corrected counts (in the example accessed via `GetAssayData(immune.combined.sct, assay = "SCT", slot = "counts")`) are not directly comparable between samples that have been sequenced to different depth. This is the case because in the context of integration SCTransform is run per sample and the corrected counts are based on the median depth.
However, when running `diff_mean_test_conserved` we are testing for DE genes within each sample and then combine the test results. Since there are no between-sample comparisons, the difference in depth does not matter.

I hope this makes sense. In short, ignore the paragraph and run the integration as outlined in the [Seurat vignette](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1) and the DE test as outlined in [my DE vignette](https://rawgit.com/ChristophH/sctransform/supp_html/supplement/np_diff_mean_test.html#Example_6:_Conserved_markers_after_integration)
