### ISSUE TITLE
ERCC Spike-Ins

### ISSUE THREAD

**Issue by jasenjackson** [ChristophH/sctransform#11]
Can ERCC spike-in counts still be used to control for batch effects? I know sctransform was developed to _replace_ between-sample normalization methods, but could known factors of unwanted variation using negative control genes(say generated from [RUVseq](https://bioconductor.org/packages/release/bioc/html/RUVSeq.html)) still be included as an additional parameter during regression?

**Comment by ChristophH** [comment]
In theory we can regress out any cell-specific continuous variable. At the moment we use log(nUMI), which is working quite well and seems to capture the technical effect of sequencing depth difference between cells. If you turn ERCC spike-ins (or negative control genes) into a continuous score, you can regress that out instead of log(nUMI).
