### ISSUE TITLE
Unexpected loss of genes

### ISSUE THREAD

**Issue by kohlkopf** [ChristophH/sctransform#19]
I'm attempting to run `sctransfrom()` in a Seurat workflow immediately after `Read10x()` and `CreateSeuratObject()`. I get repeated output of `iteration limit reached`, followed by `Error in [<-.data.frame(*tmp*, i[index], value = list(c(0.0133580214257373, : replacement element 1 has 20881 rows, need 22986`. I have 22,986 features in this object, but somehow some genes are going missing. The function fails, I can't proceed with the analysis.

Could it be a feature name issue i.e. Genbank vs Entrez, or perhaps underscores/hyphen issues? 

I have no issues going through the standard Seurat v3 workflow with this object.

**Comment by ChristophH** [comment]
Please re-install both sctransform and Seurat and try again. We've had some issues with how we handle the case where the `counts`, `data` and `scale.data` slots of an assay in Seurat have different numbers of rows. This should be fixed in the latest versions on github. It's not a feature name issue.

**Comment by kohlkopf** [comment]
I had installed `sctransform` from CRAN. Uninstalling and reinstalling both `Seurat` and `sctransform` from Github did the trick. Thanks! 

It seems the `iteration limit reached` warning is unrelated.
