### ISSUE TITLE
alevin non-integer count data

### ISSUE THREAD

**Issue by alexvpickering** [ChristophH/sctransform#28]
What is the best approach for `alevin`'s non-integer quantification data? Running it through `sctransform` gives multiple warnings like this: 

`In dpois(y, mu, log = TRUE) : non-integer x = 2.333333`.

Would it be better to round non-integers, leave them as they are, or just inappropriate to use `sctransform`? Thank you

**Comment by ChristophH** [comment]
Since I have not tested the package using non-integer data, I cannot recommend using it on alevin output directly. Rounding might be the way to go. If you can recommend some good alevin datasets to test, I will take a look.

Having said that, it seems that despite the warning, normalization still works with non-integer observations (tested on sparse data with lots of zeros), but takes significantly longer (3 to 4 times as long) to run. `glm()` must do something special when `family = poisson` is set and the response variable is non-integer, same is true for `glm.nb()`.

**Comment by ltosti** [comment]
Hi @ChristophH ,

Just a clarification: you said you haven't tested ```sctransform``` on non-integer observations - but is it correct that the pancreas datasets you used in the tutorial actually contain non-integer datasets?

**Comment by ChristophH** [comment]
Absolutely right. With tutorial I assume you mean the [integration tutorial](https://satijalab.org/seurat/v3.1/integration.html).  Part of data was also used in the paper (supplement). I didn't look closely at the 'raw counts' for that dataset and they are indeed non-integer values. So, as I said above, normalization works with non-integer observations (or at least it looks like it does), The method was not designed with non-integer data in mind, hence the 'not tested' comment above.
