### ISSUE TITLE
scTransform with multiple samples in each batch

### ISSUE THREAD

**Issue by alextamburino** [ChristophH/sctransform#32]
Hi,

Thank you for excellent SCTransform module and clear vignette including IntegrateData.

How do you best apply SCTransform when you have multiple samples in each batch?
1) Run SCTransform on each sample then merge each batch of samples into a single object
2) Merge each batch of samples into a single object then run SCTransform

How do you use IntegrateData with multiple samples in each batch?
1) Run on each sample (as in the split.by="Tech" vignette)
2) Merge each batch of samples into a single object then Integrate all merged batch objects?

Thank you for your time,
Alex

**Comment by ChristophH** [comment]
Hi Alex,
Thank you for your interest in the package.
Generally, I'd combine all samples across batches by simply merging. If common cell types separate due to batch effect, merge samples per batch and try an integration approach as outline [here](https://satijalab.org/seurat/v3.0/integration.html).
If this does not answer your question try looking in the [Seurat](https://github.com/satijalab/seurat/issues) issues, as this is really a workflow specific question outside the scope of the issue tracker for this package.
Best, Christoph

**Comment by alextamburino** [comment]
Hi Christoph,

That's perfectly clear. Thanks for your time.

Best,
Alex

**Comment by ConDem94** [comment]
Hi Alex,

Have you found a solution to this? I am in a similar situation.

From my understanding, sctransform normalizes based on sequencing depth and generates corrected counts. Since each sample has different sequencing depths, it makes sense to:
1) Split the merged seurat to individual samples (not batch (tech)), 
2) Perform sctransform and regressing out variables (mito, g2m, s, etc), 
3) Identify shared variable features, 
4) Merge dataset to seuratobject
5) Apply integration features to merged seurat object
6) Run harmony by batch/tech.

BW,
Tinos
