### ISSUE TITLE
dealing with low quality cell

### ISSUE THREAD

**Issue by MichaelPeibo** [ChristophH/sctransform#33]
Hi @ChristophH 
Very powerful package! Actually I have paid attention to your analysis method since 'Developmental diversification of cortical inhibitory interneurons, Nature 555, 2018.'

I have a question related to how SCTransform deals with low quality cell. 
Since counts have been corrected after running SCT, do I need prefilter low quality cell(low counts, low genes)? 

Thanks!

**Comment by ChristophH** [comment]
Hi

Thank you for your interest in the method. With SCTransform you may be able to lower the thresholds for 'number of molecules detected' compared to log-normalization, because SCTransform does a better job at normalizing across a wide range of sequencing depths within a sample. However, there is a limit under which the cells are not informative enough. Where exactly that limit is will depend on your data. 

So, yes, you still need to prefilter, but maybe not as aggressively. Other obvious problems with the data (e.g. very high fraction of mitochondrial reads) will have to be addressed regardless of the normalization method used.

**Comment by MichaelPeibo** [comment]
Thanks for reply!
I will try as you described.
