### ISSUE TITLE
Error in h(simpleError(msg, call)) when I was running SCTransform

### ISSUE THREAD

**Issue by HuaZou** [ChristophH/sctransform#81]
Hi, when I was running this code:
```R
for (i in 1:length(split_seurat)) {
  split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = TRUE)
  split_seurat[[i]] <- SCTransform(split_seurat[[i]], verbose = FALSE)
}
```
it produced an error: 
```bash
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
```

It happened when I used a small mount of cells (50 cells per dataset) to run the data analysis workflow for practicing, so I wonder whether **SCTransform** could only be applied on big data?  would someone give me some advice?

**Comment by ChristophH** [comment]
First, why do you call `NormalizeData` and `SCTransform` on the same Seurat object? It's unusual - one either wants log-normalization (then you would call `NormalizeData`) or sctransform normalization (call `SCTransform`).

Regarding the number of cells, I cannot give you a specific lower bound. You would have to try and carefully explore the results. 

You could also try the develop version of the sctransform package to see if the error you are getting is due to one of the known issues that have been fixed. See https://github.com/ChristophH/sctransform/issues/76 for details.
