### ISSUE TITLE
Question: FindIntegrationAnchors, scale = FALSE?

### ISSUE THREAD

**Issue by lima1** [ChristophH/sctransform#9]
Thanks for all the great work. I'm testing SCTransform upstream of FindIntegrationAnchors and was wondering if it's recommended to set scale = FALSE when the reference.list was normalized by your function.

**Comment by satijalab** [comment]
Yes, that is correct. In the FindIntegrationAnchors call, we recommend setting scale = FALSE when the data has been preprocessed with sctransform.

The reason is that ScaleData (if scale = TRUE), scales all genes to have unit variance. SCTransform does not do this, and the variance of the gene is related to its 'biological heterogeneity' (variance unexplained by technical factors).
